### ISSUE TITLE
не импортируется модуль

### ISSUE THREAD

**Issue by mik999** [witomin/Y360Management#2]
Import-Module: 
Line |
   5 |  Import-Module Y360Management
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The module to process 'Y360Management.dll', listed in field 'NestedModules' of module manifest 'C:\program files\powershell\7\
Modules\Y360Management\Y360Management.psd1' was not processed because no valid module was found in any module directory.

и этой длл там по факту нет. Где ее взять?

**Comment by witomin** [comment]
Скачайте последнюю версию.
https://github.com/witomin/Y360Management/releases/download/0.4.1/Y360Management.zip

Поместите файлы в папку C:\Program Files\PowerShell\7\Modules\Y360Management

Выполните команду:
Import-Module Y360Management

Затем: 
Connect-y360

**Comment by witomin** [comment]
Получилось ли импортировать модуль?

**Comment by mik999** [comment]
Да, всё супер, спасибо!

ср, 14 июн. 2023 г., 19:22 witomin ***@***.***>:

**Comment by witomin** [comment]
Проблема решена
